/!! Start of file                                                               
/!! Content type:  TCL                                                          
/!! Sequence:      472                                                          
/!! Records:       2                                                            
/!! Generated:     04/02/2020                                                   
/!! Exporter:      RJIS RjEhrFrs v 4.6.5                                        
13112299910111991FIRST   1ST
23112299910111991STANDARDSTD
/!! End of file (04/02/2020)